### PR TITLE
Implement EnqueueIn and EnqueueAt

### PR DESCRIPTION
**Pull request by Soulou**
Hi everybody,

I took the initiative to solve #22 after this long inactivity period, this is a first working verison, please tell me what could be improved.

This PR uses the same mecanism as the retry middleware using the default scheduler running with the `namespace:schedule` zset.

The default polling rythm is 15 seconds, it may be long for some people, what do you thing about making it configurable?

-- Leo

### CODE REVIEW

**Comment by hamin** [comment]
@Soulou @jrallison we are actually in need of this feature, is the travis Build still failing for this PR?

**Comment by Soulou** [comment]
@hamin @jrallison Rebased and updated to pass tests, it's mergeable again :+1:

**Comment by hamin** [comment]
:+1:  @jrallison can we get this merged in ?

**Comment by jrallison** [comment]
Hey @Soulou,

Thanks so much for working on this!

I do have concerns with the changes to `scheduled.rb`, `scheduled_test.rb`, `middleware_retry.go`, and the new `enqueueAt` method.

All of those are either inserting or pulling items out of the sorted set using timestamps with nanosecond precision. Sidekiq (and our scheduling up to this point) uses timestamps with second precision as scores in the redis sorted set.

Anyone updating to this version of go-workers, will see all of their scheduled jobs process immediately, as we're now processing all items in the sorted set from `-inf` to `now` (in nanoseconds) which will include any reasonable timestamp with a precision in seconds.

This seems like a fairly significant change from how Sidekiq performs, as well as a strong backward incompatible change for go-workers.

I'd encourage us to get this passing without changing `scheduled_test.rb` and adding tests for `enqueueAt`, specifically that it enqueues it with the correct timing.

Thanks!

Cheers,
John

**Comment by jrallison** [comment]
Sorry, a correction: Sidekiq uses `Time.now.to_f.to_s` by default to query for scheduled jobs.

In ruby, this evaluates to `1430758925.434581` in my terminal.

This does have higher resolution than seconds, however it also works for jobs enqueued with second precision and maintains backwards compatibility.

**Comment by jrallison** [comment]
After re-reading the change set, it seems that may be what you're attempting to do, but it doesn't seem to be correct.

We're using a Sidekiq consistent conversion of a time to a float in EnqueueWithOptions: `float64(time.Now().UnixNano()) / 1000000000` (https://github.com/jrallison/go-workers/blob/master/enqueue.go#L49)

The implementation of `toNano` is returning a float with an integer precision of milliseconds rather than seconds.

Also, `duration.Nanoseconds()` will return an integer. So adding/subtracting that from a float timestamp will result in a different meaning than we'd expect, I believe.

https://play.golang.org/p/tI_WiDjAGg

**Comment by Soulou** [comment]
Hi there, I'm going to run further test of integration with sidekiq, I'll patch what has to be patched!

**Comment by Soulou** [comment]
You can follow my work there: https://github.com/Soulou/go-workers-sidekiq-example

**Comment by Soulou** [comment]
Here we are, I've rewritten most of my change, more verbose names, please tell me what you're thinking of it, should be all right now.

**Comment by jrallison** [comment]
Hey Soulou,

This looks great! The only remaining issue is the definition of:

```
func durationToSecondsWithNanoPrecision(d time.Duration) float64 {
   return float64(d.Nanoseconds())
}
```

This isn't returning data on the same resolution as the other methods. For instance, passing `time.Second` should return the float `1.000000000` or near abouts. When combining that with the current time (like you do for `waitDuration` here: https://github.com/Scalingo/go-workers/commit/848ed232930bb0300e7ed22c7c838fc0efc5e54a#diff-e3da027e52fa684d9b863be51d846da8R37), you'll get a result much further in the future than you'd expect.

The scheduled test is verifying with the same faulty logic (adding `durationToSecondsWithNanoPrecision` to the current time which hides the error). Ideally the test is using more absolute methods of verifying the code is doing the right thing.

I'd encourage you to get the scheduled test to pass with zero changes (move back to adding/subtracting 60 seconds rather than passing it through `durationToSecondsWithNanoPrecision`), to ensure your logic is behaving correctly.

Other than that, it all looks good to go! I think with that one change, it'll be ready to merge in.

Thanks again for all your work on this!

Cheers,
John

**Comment by Soulou** [comment]
Done, I feel silly not having thinking that before, should be all right now.

**Comment by jrallison** [comment]
Fixes #22 

Thanks so much, @Soulou!

**Comment by hamin** [comment]
@Soulou @jrallison WAHOO nice guys thanks :)

**Pull request merged**
