### PR TITLE
Handle stats panic

### PR DESCRIPTION
**Pull request by hamin**
The Stats endpoint was panicking because of nil failed/processed jobs.

### CODE REVIEW

**Comment by hamin** [comment]
@jrallison looks like I messed up the pull request a bit, if you want u can close the #40 since this pull requests contains both. Let me know

**Comment by hamin** [comment]
@jrallison any chance this pull request can be merged into the project?

**Comment by jrallison** [comment]
Hey @hamin sorry for the delay. Thanks for this!

**Comment by hamin** [comment]
@jrallison no problem :)

**Pull request merged**
