### PR TITLE
exit all worker/fetcher/manager correctly

### PR DESCRIPTION
**Pull request by LYY**
I have a production environment based on go-workers. I used [runit](http://smarden.org/runit/) for daemon. While it run a few days,  I send "term" signal to stop it, but it can't stopped.

I check code of go-workers, and guess the bug is worker/fetcher/manager not exit correctly. 

About "for" "select" break:
test1: http://play.golang.org/p/l01ImEBCwv
test2: http://play.golang.org/p/pLQarqtZdg

### CODE REVIEW

**Comment by LYY** [comment]
need test more

**Comment by LYY** [comment]
many changs

**Comment by Soulou** [comment]
Why closing that ? @LYY

**Comment by LYY** [comment]
@Soulou I change too much codes for my own pupurpose, so this PR can't to merge. I will create a new branch to commit the fixes.

**Comment by LYY** [comment]
@Soulou #60 new pr

**Pull request closed without merging**
